.\" this is note
.TH TEST 1 "9 FEB 2017" "ANSWERYWJ"
.SH NAME
test \- do something

.SH SYNOPSIS
\fBresample\fR 
[
.I options
]
inputFile
[outputFile]

.SH DESCRIPTION
The \fBtest\fR program takes ...

.SH OPTIONS

.BI \-a " sadas"

Balabalabala,
.IR sasad.

.SH USAGE
To do something, the command
line would look something like

	test
or
	test

.SH BUGS
some bugs 

.SH AUTHORS
Written by AnSwErYWJ.

.SH REPORTING BUGS 
Report bugs to ...

.SH COPYRIGHT

.SH SEE ALSO
Source code and further documentation may be found at

    https://github.com/AnSwErYWJ/DogFood/tree/master/make

.SH HISTORY
Say a story
